/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/UnitTests/JUnit5TestClass.java to edit this template
 */
package dao.asset;

import java.util.List;
import model.asset.Asset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.DisplayName;

/**
 *
 * @author An
 */
public class AssetDaoTest {

    private static final String DB_URL = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MSSQLServer";
    private static Connection conn;
    private AssetDao assetDao;

    //  Tạo database ảo 
    @BeforeAll
    static void initDatabase() throws Exception {
        // Tạo DB ảo trong RAM 
        conn = DriverManager.getConnection(DB_URL, "sa", "");
        // Tạo bảng 
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE AssetCategories ("
                    + "CategoryId BIGINT PRIMARY KEY, "
                    + "CategoryName VARCHAR(255))");
            st.execute("CREATE TABLE Rooms ("
                    + "RoomId BIGINT PRIMARY KEY, "
                    + "RoomName VARCHAR(255), "
                    + "Location VARCHAR(255))");
            st.execute("CREATE TABLE Users ("
                    + "UserId BIGINT PRIMARY KEY, "
                    + "FullName VARCHAR(255))");
            st.execute("CREATE TABLE Assets ("
                    + "AssetId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "AssetCode VARCHAR(50), "
                    + "AssetName VARCHAR(255), "
                    + "Unit VARCHAR(50), "
                    + "CategoryId BIGINT, "
                    + "SerialNumber VARCHAR(100), "
                    + "Model VARCHAR(100), "
                    + "Brand VARCHAR(100), "
                    + "OriginNote VARCHAR(500), "
                    + "PurchaseDate DATE, "
                    + "ReceivedDate DATE, "
                    + "ConditionNote VARCHAR(500), "
                    + "Status VARCHAR(50), "
                    + "CurrentRoomId BIGINT, "
                    + "CurrentHolderId BIGINT, "
                    + "IsActive BOOLEAN DEFAULT TRUE, "
                    + "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                    + "UpdatedAt TIMESTAMP)");
        }
        // Thêm dữ liệu mẫu 
        seedData();
    }

    //  Dữ liệu mẫu
    private static void seedData() throws SQLException {
        try (Statement st = conn.createStatement()) {
            // Danh mục
            st.execute("INSERT INTO AssetCategories VALUES (4, N'Bàn ghế')");
            st.execute("INSERT INTO AssetCategories VALUES (5, N'Thiết bị điện tử')");
            // Phòng
            st.execute("INSERT INTO Rooms VALUES (1, N'Phòng 101', N'Tầng 1')");
            // Người dùng
            st.execute("INSERT INTO Users VALUES (1, N'Nguyễn Văn A')");
            // Asset 1: có đầy đủ thông tin, IN_STOCK, active
            st.execute("INSERT INTO Assets "
                    + "(AssetId, AssetCode, AssetName, Unit, CategoryId, SerialNumber, "
                    + "Model, Brand, OriginNote, PurchaseDate, ReceivedDate, "
                    + "ConditionNote, Status, CurrentRoomId, CurrentHolderId, IsActive) "
                    + "VALUES (11, 'TS-001', N'Bàn học sinh', N'Cái', 4, 'SN001', "
                    + "'ModelA', 'BrandX', N'Mua mới', '2025-01-15', '2025-02-01', "
                    + "N'Tốt', 'IN_STOCK', 1, 1, TRUE)");
            // Asset 2: không có room/holder, DISPOSED, inactive
            st.execute("INSERT INTO Assets "
                    + "(AssetId, AssetCode, AssetName, Unit, CategoryId, SerialNumber, "
                    + "Model, Brand, Status, CurrentRoomId, CurrentHolderId, IsActive) "
                    + "VALUES (12, 'TS-002', N'Ghế cũ', N'Cái', 4, 'SN002', "
                    + "'ModelB', 'BrandY', 'DISPOSED', NULL, NULL, FALSE)");
            // Asset 3: category khác, IN_USE
            st.execute("INSERT INTO Assets "
                    + "(AssetId, AssetCode, AssetName, Unit, CategoryId, SerialNumber, "
                    + "Model, Brand, Status, IsActive) "
                    + "VALUES (13, 'TS-003', N'Máy chiếu', N'Cái', 5, 'SN003', "
                    + "'ModelC', 'BrandZ', 'IN_USE', TRUE)");
        }
    }

    @BeforeEach
    void setUp() throws SQLException {
        // Tạo connection mới cho mỗi test (vì DAO dùng try-with-resources sẽ tự đóng)
        Connection testConn = DriverManager.getConnection(DB_URL, "sa", "");
        assetDao = new AssetDao(testConn);
    }

    @AfterAll
    static void closeDatabase() throws Exception {
        if (conn != null) {
            conn.close();
        }
    }

    //  TEST findById()
    @Test
    @DisplayName("findById with existing id returns asset")
    void findByIdExist() throws SQLException {
        int id = 11;                                  // input
        boolean expected = true;                      // mong đợi: tìm thấy
        Asset result = assetDao.findById(id);
        boolean actual = (result != null);            // kết quả thực tế
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("findById with non-existing id returns null")
    void findByIdNotExist() throws SQLException {
        int id = 999999;
        Asset expected = null;
        Asset actual = assetDao.findById(id);
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("findById returns correct asset name")
    void findByIdCheckName() throws SQLException {
        int id = 11;
        String expected = "Bàn học sinh";
        Asset result = assetDao.findById(id);
        String actual = result.getAssetName();
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("findById returns correct status")
    void findByIdCheckStatus() throws SQLException {
        int id = 11;
        String expected = "IN_STOCK";
        Asset result = assetDao.findById(id);
        String actual = result.getStatus();
        assertEquals(expected, actual);
    }

    //  TEST searchAssets() 
    @Test
    @DisplayName("searchAssets with non-existing keyword returns empty list")
    void searchNotFound() throws SQLException {
        String keyword = "XYZKHONGTONTAI999";
        int expected = 0;
        List<Asset> result = assetDao.searchAssets(keyword, null, null, null);
        int actual = result.size();
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("searchAssets with status IN_STOCK returns only IN_STOCK assets")
    void searchByStatus() throws SQLException {
        String status = "IN_STOCK";
        String expected = "IN_STOCK";
        List<Asset> result = assetDao.searchAssets(null, status, null, null);
        String actual = result.get(0).getStatus();
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("searchAssets with existing categoryId returns assets of that category")
    void searchByCatId() throws SQLException {
        Long catId = 4L;
        long expected = 4;
        List<Asset> result = assetDao.searchAssets(null, null, catId, null);
        long actual = result.get(0).getCategoryId();
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("searchAssets with isActive true returns only active assets")
    void searchByActiveTrue() throws SQLException {
        Boolean isActive = true;
        boolean expected = true;
        List<Asset> result = assetDao.searchAssets(null, null, null, isActive);
        boolean actual = result.get(0).isIsActive();
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("searchAssets with isActive false returns only inactive assets")
    void searchByActiveFalse() throws SQLException {
        Boolean isActive = false;
        boolean expected = false;
        List<Asset> result = assetDao.searchAssets(null, null, null, isActive);
        boolean actual = result.get(0).isIsActive();
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("searchAssets with keyword and status combined filters correctly")
    void searchByKeywordAndStatus() throws SQLException {
        String keyword = "Bàn";
        String status = "IN_STOCK";
        List<Asset> result = assetDao.searchAssets(keyword, status, null, null);
        if (!result.isEmpty()) {
            String actualStatus = result.get(0).getStatus();
            assertEquals("IN_STOCK", actualStatus);
            // Kiểm tra tên có chứa keyword
            boolean containsKeyword = result.get(0).getAssetName().contains(keyword);
            assertEquals(true, containsKeyword);
        }
    }

    @Test
    @DisplayName("searchAssets with empty keyword returns all assets")
    void searchByEmptyKeyword() throws SQLException {
        String keyword = "";                             
        boolean expected = true;                        
        List<Asset> result = assetDao.searchAssets(keyword, null, null, null);
        boolean actual = result.size() > 0;             
        assertEquals(expected, actual);
    }

    @Test
    @DisplayName("searchAssets with categoryId 0 returns all assets")
    void searchByCatIdZero() throws SQLException {
        Long catId = 0L;                               
        boolean expected = true;                         
        List<Asset> result = assetDao.searchAssets(null, null, catId, null);
        boolean actual = result.size() > 0;             
        assertEquals(expected, actual);
    }

}
